language: python
# vesions
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - "pip install unittest2"  
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install nose"
# command to run tests
script:
  -python run.py
  - nose --with-coverage --cover-package=Tests

after_success:
  - coveralls
