language: python
# vesions
python:
  - "3.6"
cache: pip
# command to install dependencies
install:
  - "pip install unittest2"  
  - "pip install coveralls"
  - "pip install coverage"
  - "pip install nosetests"
# command to run tests
script:
  -python -run.py
  - nosetests --with-coverage

after_success:
  - coveralls
env:
  - DB=postgres
  - SH=bash
  - PACKAGE_VERSION="1.0.*"